### ISSUE TITLE
导出数据时，目录某章节含有’时，那个章节无法正常识别

### ISSUE THREAD

**Issue by Icarus-Alpha** [jooooock/wrx#1]
导出数据时，目录某章节含有`'`时，那个章节无法正常识别。
例如 《Java性能权威指南（第2版）》这本书，“O'Reilly Media，Inc.介绍”，章节无法正确识别，下载数据。
![image](https://github.com/jooooock/wrx/assets/73479298/a8902fde-97cf-42e0-aa41-4ac30e2eea73)
![image](https://github.com/jooooock/wrx/assets/73479298/2ce22f4f-75c7-45a4-a875-667e4f27df99)

**Comment by jooooock** [comment]
这个是因为页面显示的章节标题与接口返回的不匹配，导致这个章节被认为是未下载的(其实数据已经被下载了，可直接导出，数据是完整的)。

这个需要看看是否是普遍现象(标题中含有单引号或双引号，但目录弹框里面不显示单引号)，如果是的话，我会在匹配逻辑处兼容一下。

**Comment by Icarus-Alpha** [comment]
> 这个是因为页面显示的章节标题与接口返回的不匹配，导致这个章节被认为是未下载的(其实数据已经被下载了，可直接导出，数据是完整的)。
> 
> 这个需要看看是否是普遍现象(标题中含有单引号或双引号，但目录弹框里面不显示单引号)，如果是的话，我会在匹配逻辑处兼容一下。

确实，虽然那个章节显示未被下载，但是实际数据是包含那个章节的。下载为epub文件后，也是完整的
