### ISSUE TITLE
加载插件报错

### ISSUE THREAD

**Issue by xuze1993** [jooooock/wrx#10]
0.53版本加载插件报错：  weread.json: Internal error while parsing rules.  无法加载清单。

**Comment by jooooock** [comment]
我这边无法重现，你把你解压后的`rules/weread.json`内容贴上来看看

**Comment by xuze1993** [comment]
[
    {
        "id": 1,
        "priority": 1,
        "condition": {
            "urlFilter": "7.5853f5ce.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.5853f5ce.js"
            }
        }
    },
    {
        "id": 2,
        "priority": 1,
        "condition": {
            "urlFilter": "7.68f5013a.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.68f5013a.js"
            }
        }
    },
    {
        "id": 3,
        "priority": 1,
        "condition": {
            "urlFilter": "7.8e1d03c5.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.8e1d03c5.js"
            }
        }
    },
    {
        "id": 4,
        "priority": 1,
        "condition": {
            "urlFilter": "7.905964f9.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.905964f9.js"
            }
        }
    },
    {
        "id": 5,
        "priority": 1,
        "condition": {
            "urlFilter": "7.cfe384e5.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.cfe384e5.js"
            }
        }
    },
    {
        "id": 6,
        "priority": 1,
        "condition": {
            "urlFilter": "7.f8cd399c.js"
        },
        "action": {
            "type": "redirect",
            "redirect": {
                "extensionPath": "/overrides/weread/7.f8cd399c.js"
            }
        }
    }
]

**Comment by xuze1993** [comment]
[weread.json](https://github.com/user-attachments/files/16739559/weread.json)

**Comment by jooooock** [comment]
这个文件好像也没什么问题

**Comment by xuze1993** [comment]
找到问题了。我为了省事把插件解压在chrome的默认安装目录下，读取就会报错。随便找个其他地方解压加载就可以了，一切正常
