### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by changanshichangan** [jooooock/wrx#12]
![S40830-13032067_com lemurbrowser exts](https://github.com/user-attachments/assets/50d4f3e5-052b-48a0-88a8-884e5c513077)
![S40830-13084800_com tencent weread](https://github.com/user-attachments/assets/c81b4d80-16ee-4d3b-97f4-14632de6905d)

**Comment by jooooock** [comment]
收到

**Comment by jooooock** [comment]
跟 [这个](https://github.com/jooooock/wrx/issues/1) 的原因是一样的，标题中含有单引号，但是页面渲染时没有渲染出单引号，导致数据不一致。

我这里做一下兼容

**Comment by jooooock** [comment]
已修复
