### ISSUE TITLE
解密完下载不下来

### ISSUE THREAD

**Issue by strugglesharp** [jooooock/wrx#34]
点了下载一直转圈圈.
如果自己不想维护了, 可以开源出来让别人接力.
如果彻底不想做了. 那就干脆把这个项目关了.  费劲巴拉的把缓存跑出来. 第二步走不通, 让人郁闷.

**Comment by strugglesharp** [comment]
这个功能确定是没法商业化的, 我不知道解密功能做好了又不开源的原因是什么

**Comment by jooooock** [comment]
👌🏻，我接受你的建议，稍后我会在readme中说明项目当前的情况。

如果浪费了你的时间，我对此表示抱歉。

**Comment by strugglesharp** [comment]
> 👌🏻，我接受你的建议，稍后我会在readme中说明项目当前的情况。
> 
> 如果浪费了你的时间，我对此表示抱歉。

毕竟用爱发电, 我也不能要求太多.
