### ISSUE TITLE
图书内图片丢失

### ISSUE THREAD

**Issue by YJY07** [jooooock/wrx#5]
图书内所有图片丢失，显示not found

**Comment by gigihubb** [comment]
希望能修复，谢谢！

**Comment by jooooock** [comment]
我随便试了一本包含图片的书，并没有复现，请提供对应的json文件

**Comment by gigihubb** [comment]
[比较文学与世界文学（第八期）.json](https://github.com/jooooock/wrx/files/15409707/default.json)

**Comment by jooooock** [comment]
> [比较文学与世界文学（第八期）.json](https://github.com/jooooock/wrx/files/15409707/default.json)

我用你这个json文件导出的时候，发现服务器在下载图片时非常慢，不知道是不是微信有什么限制。

然后等了好久下载下来之后，找到一处图片有问题的情况，是图片地址不正确，如下图：

![image](https://github.com/jooooock/wrx/assets/156505552/ef3b3773-e8de-4beb-898e-62942d5f51fc)

具体细节等我有空看一下服务器下载图片的逻辑

**Comment by gigihubb** [comment]
谢谢！不只一处图片不显示。未能下载的图片在Book Browser 一栏下的Misc文件夹里可以看到。

**Comment by edisonzf2020** [comment]
我也是，解密和导出非常的慢，最后报失败。
西方叙事学：经典与后经典.json

**Comment by jooooock** [comment]
新版导出已完成，可以用新版试一下还会不会有问题
@YJY07 @gigihubb @edisonzf2020
