### ISSUE TITLE
下一页不能自动翻页

### ISSUE THREAD

**Issue by changanshichangan** [jooooock/wrx#6]

**Comment by jooooock** [comment]
更新最新版本

**Comment by jooooock** [comment]
细节可以查看 readme 中 [为什么不发布到插件市场，然后自动更新？而采用这种手动更新的“笨拙”方式？](https://github.com/jooooock/wrx?tab=readme-ov-file#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E5%8F%91%E5%B8%83%E5%88%B0%E6%8F%92%E4%BB%B6%E5%B8%82%E5%9C%BA%E7%84%B6%E5%90%8E%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E8%80%8C%E9%87%87%E7%94%A8%E8%BF%99%E7%A7%8D%E6%89%8B%E5%8A%A8%E6%9B%B4%E6%96%B0%E7%9A%84%E7%AC%A8%E6%8B%99%E6%96%B9%E5%BC%8F) 的说明。
